# Generated by Django 5.0.4 on 2024-04-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_customlisting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomListing',
        ),
    ]
